/* ============================================================
   "Check your understanding" question bank (data only).
   One quiz per NESA subheading, keyed "<page>-<part number>".
   Each question: q, options[], answer (index), why (explanation).
   Rendered by js/quiz.js into <div class="quiz" data-quiz="…">.
   ============================================================ */
window.HSC_QUIZZES = {
  /* ── Programming fundamentals ── */
  'pf-1': [
    { q: 'A team confirms the app runs at 60 fps on a Raspberry Pi 4 before designing anything. Which development step is this?',
      options: ['Requirements definition', 'Determining specifications', 'Integration', 'Maintenance'], answer: 1,
      why: 'Specifications set technical constraints such as hardware, performance and memory limits.' },
    { q: 'What is the main benefit of a pull request on GitHub?',
      options: ['It deletes old branches automatically', 'It lets teammates review code before it is merged', 'It makes code run faster', 'It backs up the database'], answer: 1,
      why: 'Pull requests support peer review, catching errors before code reaches the main branch.' },
    { q: 'Releasing version 1.1 to fix a bug found after launch belongs to which step?',
      options: ['Installation', 'Testing and debugging', 'Maintenance', 'Design'], answer: 2,
      why: 'Maintenance is the ongoing work of fixing bugs and adding features after deployment.' },
  ],
  'pf-2': [
    { q: 'Binary search keeps halving the list it searches. Which strategy is this?',
      options: ['Backtracking', 'Divide and conquer', 'Bottom-up design', 'Iteration only'], answer: 1,
      why: 'Divide and conquer splits a problem into smaller sub-problems of the same kind.' },
    { q: 'In pseudocode, which line calls a function rather than a procedure?',
      options: ['printReceipt(order)', 'total ← total + getPrice(item)', 'saveFile(data)', 'showMenu()'], answer: 1,
      why: 'A function returns a value, so it is used inside an expression. Procedures are called on their own line.' },
    { q: 'You trace an algorithm by hand, recording each variable in a table. What is this called?',
      options: ['Peer checking', 'Desk checking', 'Refinement', 'Profiling'], answer: 1,
      why: 'A desk check (dry run) traces the algorithm step by step with sample data.' },
  ],
  'pf-3': [
    { q: 'What is 1011 in decimal?',
      options: ['9', '11', '13', '1011'], answer: 1,
      why: '8 + 0 + 2 + 1 = 11.' },
    { q: 'Which data type is best for an Australian mobile number such as 0412 345 678?',
      options: ['Integer', 'Real', 'String', 'Boolean'], answer: 2,
      why: 'You never do arithmetic on phone numbers, and an integer would drop the leading zero.' },
    { q: "What is −5 in 8-bit two's complement?",
      options: ['10000101', '11111010', '11111011', '00000101'], answer: 2,
      why: 'Write 5 (00000101), invert the bits (11111010), then add 1: 11111011.' },
  ],
  'pf-4': [
    { q: 'A program accepts marks from 1 to 100. Which set tests the boundaries best?',
      options: ['50, 60, 70', '0, 1, 100, 101', '"fifty", −5', '1, 2, 3'], answer: 1,
      why: 'Boundary testing checks values on and just outside each limit, where off-by-one errors hide.' },
    { q: 'Code runs without crashing but a mark of exactly 50 is shown as a fail. What kind of error is this?',
      options: ['Syntax error', 'Runtime error', 'Logic error', 'Compilation error'], answer: 2,
      why: 'The code is valid and runs, but the logic (probably < instead of <=) is wrong.' },
    { q: 'Which data structure suits an undo feature?',
      options: ['Stack', 'Hash table', 'Sequential file', 'Two-dimensional array'], answer: 0,
      why: 'Undo needs the most recent action first: last in, first out.' },
  ],

  /* ── The object-oriented paradigm ── */
  'oop-1': [
    { q: 'Making balance private and changing it only through deposit() and withdraw() is an example of…',
      options: ['Inheritance', 'Encapsulation', 'Polymorphism', 'Generalisation'], answer: 1,
      why: 'Encapsulation bundles data with its methods and hides the data from direct access.' },
    { q: 'shape.area() works for both a Circle and a Square. Which feature makes this possible?',
      options: ['Polymorphism', 'Abstraction', 'Message passing', 'Composition'], answer: 0,
      why: 'Polymorphism lets different classes respond to the same method call in their own way.' },
    { q: 'Moving name and email from Student and Teacher into a shared Person class is…',
      options: ['Encapsulation', 'Generalisation', 'Optimisation', 'Refinement'], answer: 1,
      why: 'Generalisation identifies common traits and moves them into a parent class.' },
  ],
  'oop-2': [
    { q: 'What is a stub?',
      options: ['A comment at the top of a file', 'A placeholder subroutine used until the real one is written', 'A failed test', 'A type of loop'], answer: 1,
      why: 'Stubs let you test the rest of the program before every subroutine is finished.' },
    { q: 'Testing a program only through its inputs and outputs, without reading the code, is…',
      options: ['White-box testing', 'Black-box testing', 'Unit testing', 'Desk checking'], answer: 1,
      why: 'Black-box testing checks behaviour against expected results without looking inside.' },
    { q: 'Which practice best supports a clear and uncluttered mainline?',
      options: ['Putting all code in one long function', 'Calling well-named subroutines that each do one task', 'Using global variables everywhere', 'Avoiding comments'], answer: 1,
      why: 'A short mainline that calls one-task subroutines is easier to read, test and maintain.' },
  ],

  /* ── Programming mechatronics ── */
  'mech-1': [
    { q: 'Which is an actuator?',
      options: ['Ultrasonic sensor', 'Servo motor', 'Light-dependent resistor', 'Temperature probe'], answer: 1,
      why: 'Actuators produce movement or output; sensors measure the environment.' },
    { q: 'A 2000 mAh battery powers a system that draws 500 mA. Roughly how long will it last?',
      options: ['2 hours', '4 hours', '10 hours', '25 hours'], answer: 1,
      why: '2000 ÷ 500 = 4 hours, before allowing for battery ageing and temperature.' },
    { q: 'Why give motors their own power supply?',
      options: ['Motors need less voltage', 'Their current surges can reset the microcontroller', 'It makes wiring diagrams shorter', 'Sensors only work on batteries'], answer: 1,
      why: 'Sudden motor current can cause a brownout that restarts the controller.' },
  ],
  'mech-2': [
    { q: 'Which is a closed loop system?',
      options: ['A toaster on a timer', 'A sprinkler that runs every day at 6 am', 'A thermostat that reads the temperature and adjusts heating', 'A fan with an on/off switch'], answer: 2,
      why: 'Closed loop control uses sensor feedback to correct its output.' },
    { q: 'In closed loop control, the error is…',
      options: ['The setpoint minus the measured value', 'A syntax mistake', 'The battery voltage', 'The number of sensors'], answer: 0,
      why: 'The controller acts on the difference between what you want and what is happening.' },
    { q: 'An autonomous robot must mainly be able to…',
      options: ['Follow a fixed timer only', 'Sense, decide and act without a person controlling it', 'Run without code', 'Work only in simulation'], answer: 1,
      why: 'Autonomous control reads sensors, makes decisions and adapts to its environment by itself.' },
  ],
  'mech-3': [
    { q: 'Why test code in a simulator such as Wokwi before building?',
      options: ['Simulators show real friction and noise', 'It is free and safe to find logic and wiring errors early', 'Simulated code runs faster on hardware', 'Unit tests are not needed afterwards'], answer: 1,
      why: 'Simulation catches logic mistakes without risking parts, though real prototypes are still needed.' },
    { q: 'Averaging the last five sensor readings is an example of…',
      options: ['Sensor filtering', 'PWM', 'Polling', 'Opcode optimisation'], answer: 0,
      why: 'Smoothing noisy readings improves decisions and reduces actuator jitter.' },
    { q: 'Which input should use an interrupt?',
      options: ['A room temperature reading', 'An emergency stop button', 'A daily log upload', 'A light level shown on screen'], answer: 1,
      why: 'Interrupts respond immediately, which matters for safety controls.' },
  ],

  /* ── Secure software architecture ── */
  'ssa-1': [
    { q: 'Why build security into the requirements step rather than at the end?',
      options: ['It is required only by Waterfall', 'Vulnerabilities are cheaper to prevent than to fix later', 'Testing is not needed then', 'It removes the need for maintenance'], answer: 1,
      why: 'Security defined early shapes the design; fixing flaws after release costs far more.' },
    { q: 'An app used mostly by elderly people should…',
      options: ['Use complex passwords with no reset', 'Offer clear, simple security steps such as passkeys and plain-language warnings', 'Hide all error messages', 'Skip authentication'], answer: 1,
      why: "Users' capabilities and experience should shape secure design so security is actually usable." },
    { q: 'Which is a benefit of secure software?',
      options: ['Larger attack surface', 'Data protection and fewer successful attacks', 'No need for updates', 'Faster compilation'], answer: 1,
      why: 'Secure software protects data and minimises cyber attacks and vulnerabilities.' },
  ],
  'ssa-2': [
    { q: 'A teacher can edit marks but a student can only view them. Which concept is this?',
      options: ['Authentication', 'Authorisation', 'Accountability', 'Availability'], answer: 1,
      why: 'Authorisation decides what an authenticated user is allowed to do.' },
    { q: 'Running each browser tab in isolation so a malicious page cannot read your files is…',
      options: ['Hashing', 'Sandboxing', 'Session management', 'Penetration testing'], answer: 1,
      why: 'Sandboxing confines code so it cannot harm the rest of the system.' },
    { q: 'What is the best defence against SQL injection?',
      options: ['Hiding the database', 'Parameterised queries', 'Longer passwords', 'HTTPS'], answer: 1,
      why: 'Parameterised queries keep user input as data, so it can never run as SQL.' },
  ],
  'ssa-3': [
    { q: 'Which is a benefit to an enterprise of secure development practices?',
      options: ['More emergency patches', 'Greater customer trust and productivity', 'Less documentation', 'No need for testing'], answer: 1,
      why: 'Fewer incidents mean less disruption, and customers trust services with a strong record.' },
    { q: 'Collaboration helps secure development mainly because…',
      options: ['Code is written faster without review', 'Different points of view catch different risks', 'Only one person needs to understand the code', 'It removes the need for testing'], answer: 1,
      why: 'Diverse perspectives and delegated expertise improve the quality of the solution.' },
    { q: 'Which law sets rules for handling personal information in Australia?',
      options: ['Copyright Act 1968', 'Privacy Act 1988', 'Spam Act 2003', 'Corporations Act 2001'], answer: 1,
      why: 'The Privacy Act 1988 and its Australian Privacy Principles govern personal information.' },
  ],

  /* ── Programming for the web ── */
  'web-1': [
    { q: 'Which protocol and port does HTTPS normally use?',
      options: ['HTTP on 80', 'TLS-secured HTTP on 443', 'FTP on 21', 'SMTP on 25'], answer: 1,
      why: 'HTTPS is HTTP over TLS, usually on port 443.' },
    { q: 'What does DNS do?',
      options: ['Encrypts web traffic', 'Translates domain names into IP addresses', 'Stores cookies', 'Compresses images'], answer: 1,
      why: 'DNS is the internet\'s "phone book", finding the IP address for a name.' },
    { q: 'A photo\'s camera model and GPS location are examples of…',
      options: ['Metadata', 'Cipher text', 'Packets', 'Cookies'], answer: 0,
      why: 'Metadata is data that describes other data.' },
  ],
  'web-2': [
    { q: 'Why must prices be checked on the server, not only in the browser?',
      options: ['Servers are faster', 'Users can change browser code with developer tools', 'Browsers cannot do maths', 'It saves bandwidth'], answer: 1,
      why: 'Client-side code can be bypassed, so the back end must enforce business rules.' },
    { q: 'Which SQL keyword combines rows from two related tables?',
      options: ['WHERE', 'GROUP BY', 'JOIN', 'ORDER BY'], answer: 2,
      why: 'A JOIN links tables using a shared key, such as student_id.' },
    { q: 'Which feature lets a PWA work offline?',
      options: ['A service worker', 'A CSS framework', 'A template engine', 'An SQL constraint'], answer: 0,
      why: 'Service workers cache files so the app still opens without a connection.' },
  ],

  /* ── Software automation ── */
  'auto-1': [
    { q: 'Training a spam filter on emails already labelled "spam" or "not spam" is…',
      options: ['Supervised learning', 'Unsupervised learning', 'Reinforcement learning', 'Semi-supervised learning'], answer: 0,
      why: 'Supervised learning learns from examples with the correct answers attached.' },
    { q: 'Which statement about AI and ML is correct?',
      options: ['AI is a subset of ML', 'ML is a subset of AI that learns from data', 'They are unrelated', 'ML never uses data'], answer: 1,
      why: 'ML is one way to achieve AI: systems that improve by learning from data.' },
    { q: 'Which algorithm predicts a number, such as a house price?',
      options: ['Logistic regression', 'Linear regression', 'K-nearest neighbour classification', 'A decision tree with yes/no leaves only'], answer: 1,
      why: 'Linear regression predicts a continuous value; logistic regression predicts a class.' },
  ],
  'auto-2': [
    { q: 'Which model fits a curve rather than a straight line?',
      options: ['Linear regression', 'Polynomial regression', 'Logistic regression', 'K-means clustering'], answer: 1,
      why: 'Polynomial regression adds powers of the input, so the fitted line can bend.' },
    { q: 'In scikit-learn, which method trains a model?',
      options: ['predict()', 'fit()', 'score()', 'transform()'], answer: 1,
      why: 'fit() learns from training data; predict() uses the trained model.' },
    { q: 'Why is a neural network written as an object in OOP?',
      options: ['Objects run faster than functions', 'It keeps the model\'s weights with the methods that train and use it', 'Neural networks cannot use lists', 'It removes the need for data'], answer: 1,
      why: 'An object holds its state (weights) together with its behaviour (fit and predict).' },
  ],
  'auto-3': [
    { q: 'A face recognition system is much less accurate for some groups. The most likely cause is…',
      options: ['Dataset source bias', 'Overfitting to the test set only', 'Slow hardware', 'Too many layers'], answer: 0,
      why: 'Training data that under-represents some people leads to worse results for them.' },
    { q: 'Which is a positive impact of automation on the safety of workers?',
      options: ['Robots take over dangerous tasks', 'Fewer jobs in every industry', 'Higher energy use', 'Less training needed'], answer: 0,
      why: 'Automation can remove people from hazardous work.' },
    { q: 'Designing an alert so it stays calm and clear under pressure responds to…',
      options: ['Cultural protocols', 'Patterns related to acute stress response', 'Belief systems', 'Data mining'], answer: 1,
      why: 'People under stress read less and act quickly, so interfaces must be simple and direct.' },
  ],

  /* ── Software engineering project ── */
  'sep-1': [
    { q: 'A school trials new software in Year 7 before every year group uses it. Which implementation method is this?',
      options: ['Direct', 'Phased', 'Parallel', 'Pilot'], answer: 3,
      why: 'Pilot implementation tries the system with one group or site first.' },
    { q: 'Which requirement is non-functional?',
      options: ['Users can book a room', 'Pages load in under 2 seconds', 'Admins can delete bookings', 'The system emails a receipt'], answer: 1,
      why: 'Non-functional requirements describe how well the system performs, not what it does.' },
    { q: 'Checking whether a project fits the budget and deadline is assessing…',
      options: ['Scheduling and financial feasibility', 'Boundaries', 'Data types', 'Code generation'], answer: 0,
      why: 'Feasibility asks whether the project can realistically be done with the time and money available.' },
  ],
  'sep-2': [
    { q: 'Which approach suits a project whose requirements are likely to change?',
      options: ['Waterfall', 'Agile', 'Direct', 'Parallel'], answer: 1,
      why: 'Agile plans in short sprints and welcomes change after each review.' },
    { q: 'WAgile is best described as…',
      options: ['A testing tool', 'A hybrid of Waterfall planning with Agile development', 'A type of Gantt chart', 'A programming language'], answer: 1,
      why: 'WAgile keeps Waterfall gates for control but builds in Agile sprints.' },
    { q: 'Which tool shows task durations and dependencies over time?',
      options: ['Data flow diagram', 'Gantt chart', 'Structure chart', 'Class diagram'], answer: 1,
      why: 'Gantt charts schedule and track tasks against a timeline.' },
  ],
  'sep-3': [
    { q: 'Why run a programmed data backup?',
      options: ['To speed up the database', 'So data is copied automatically and can be restored', 'To replace version control', 'To test the UI'], answer: 1,
      why: 'Automated backups protect data without relying on someone remembering.' },
    { q: 'Using a payment provider instead of writing your own payment system is…',
      options: ['Outsourcing', 'Refactoring', 'Polling', 'Pilot testing'], answer: 0,
      why: 'Outsourcing hands a hard, non-core part to a trusted provider.' },
    { q: 'What should a proposed innovative solution include?',
      options: ['Finished production code', 'A prototype and UI design', 'A new programming language', 'Nothing visual'], answer: 1,
      why: 'The dot point asks for a prototype and user interface design, not a finished build.' },
  ],
  'sep-4': [
    { q: 'Comparing actual output with expected output is part of…',
      options: ['Evaluating effectiveness', 'Requirements elicitation', 'Allocating resources', 'Negotiating'], answer: 0,
      why: 'Evaluation checks whether the solution does what it should, using test results.' },
    { q: 'Which is a language-dependent optimisation in Python?',
      options: ['Using a list comprehension or sum() instead of a manual loop', 'Adding more comments', 'Renaming variables', 'Writing a Gantt chart'], answer: 0,
      why: 'Built-ins and comprehensions use Python\'s optimised internals.' },
    { q: 'Five of eight testers can\'t find the booking history. What is the best response?',
      options: ['Ignore it', 'Redesign the navigation and retest', 'Add a new unrelated feature', 'Remove the booking history'], answer: 1,
      why: 'Analyse the pattern, fix the usability issue and check the fix worked.' },
  ],
};
