#!/usr/bin/env python3
"""Build js/glossary-data.js from topics/glossary.html.

Run after editing the glossary:  python3 scripts/build-glossary.py
Also fills any term that has no example from scripts/glossary_examples.py.
"""
import html, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'scripts'))
from glossary_examples import EXAMPLES

GLOSSARY = os.path.join(ROOT, 'topics', 'glossary.html')
OUT = os.path.join(ROOT, 'js', 'glossary-data.js')

# Extra spellings students will meet in the notes.
EXTRA_ALIASES = {
    'term-agile': ['Agile'], 'term-backend': ['Backend', 'Back end'],
    'term-backlog': ['Backlog', 'Product Backlog'], 'term-cicd': ['Continuous Integration', 'Continuous Deployment'],
    'term-closed-loop': ['Closed Loop', 'Closed-loop', 'Closed-loop control'], 'term-open-loop': ['Open Loop', 'Open-loop'],
    'term-version-control': ['Version Control', 'Git'], 'term-white-box': ['White-box testing', 'White box testing'],
    'term-black-box': ['Black-box testing', 'Black box testing'], 'term-ml': ['Machine Learning'],
    'term-ai': ['Artificial Intelligence'], 'term-sql-database': ['Relational Database'],
    'term-message-passing': ['Message passing'], 'term-twos-complement': ["Two's complement", 'Twos complement'],
    'term-degrees-of-freedom': ['Degrees of freedom'], 'term-user-stories': ['User Story'],
    'term-knn': ['K-nearest neighbour', 'K-Nearest Neighbours', 'KNN'], 'term-wcag': ['WCAG', 'Web accessibility'],
}

# Everyday words that should stay in the glossary but not be auto-linked in prose.
NO_AUTOLINK = {'term-list', 'term-watch', 'term-record', 'term-tree', 'term-stack', 'term-decimal'}

text = lambda frag: html.unescape(re.sub(r'<.*?>', '', frag)).strip()
src = open(GLOSSARY, encoding='utf-8').read()

# 1. Add missing examples to the glossary page itself.
def add_example(m):
    block = m.group(0)
    tid = m.group(1)
    if 'term-example' in block or tid not in EXAMPLES:
        return block
    return re.sub(r'(</p>)', r'\1\n              <p class="term-example"><strong>Example:</strong> ' +
                  EXAMPLES[tid].replace('\\', '\\\\') + '</p>', block, count=1)

# Only terms whose card has no example yet (keeps the script idempotent).
has_example = set(re.findall(r'<div class="glossary-term" id="(term-[^"]+)">(?:(?!<div class="glossary-term").)*?class="term-example"', src, re.S))
src = re.sub(r'<div class="glossary-term" id="(term-[^"]+)">.*?</p>',
             lambda m: m.group(0) if m.group(1) in has_example else add_example(m), src, flags=re.S)
open(GLOSSARY, 'w', encoding='utf-8').write(src)

# 2. Emit the data file used by the inline popover.
terms = []
for part in re.split(r'(?=<div class="glossary-term" id=")', src)[1:]:
    tid = re.match(r'<div class="glossary-term" id="([^"]+)"', part).group(1)
    name = text(re.search(r'<h3[^>]*>(.*?)</h3>', part, re.S).group(1))
    paras = re.findall(r'<p( class="[^"]*")?>(.*?)</p>', part, re.S)
    definition = next((text(p) for c, p in paras if 'term-example' not in (c or '')), '')
    example = next((text(p).replace('Example:', '', 1).strip() for c, p in paras if 'term-example' in (c or '')), '')
    aliases = {name}
    paren = re.match(r'(.+?)\s*\((.+)\)$', name)
    if paren:
        aliases |= {paren.group(1).strip(), paren.group(2).strip()}
        aliases.discard(name)
    aliases |= set(EXTRA_ALIASES.get(tid, []))
    terms.append({'id': tid, 'name': name, 'aliases': sorted(aliases), 'def': definition, 'example': example,
                  'link': tid not in NO_AUTOLINK})

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('/* Generated by scripts/build-glossary.py from topics/glossary.html. Do not edit. */\n')
    f.write('window.HSC_GLOSSARY = ' + json.dumps(terms, ensure_ascii=False, indent=0) + ';\n')
print(f'{len(terms)} terms, {sum(1 for t in terms if t["example"])} with examples')
