# Short, concrete examples for glossary terms (Australian context).
# Used by scripts/build-glossary.py to fill terms that have no example yet.
EXAMPLES = {
 'term-abstract-class': 'A <code>Shape</code> class declares <code>area()</code> but only <code>Circle</code> and <code>Square</code> subclasses can be created.',
 'term-abstraction': 'Calling <code>send_email(to, body)</code> without knowing how the mail server connection works.',
 'term-acceptance-criteria': '"Given a wrong password three times, the account locks for 15 minutes."',
 'term-access-modifier': 'Marking <code>balance</code> as private so only <code>deposit()</code> and <code>withdraw()</code> can change it.',
 'term-accountability': 'An audit log records that user <em>jchen</em> deleted invoice #204 at 10:14 am.',
 'term-actuator': 'A servo motor that opens a greenhouse vent when the temperature rises.',
 'term-adc': 'An Arduino reading a light sensor as a number from 0 to 1023.',
 'term-agile': 'A team releases a school canteen app in two-week sprints, changing features after student feedback.',
 'term-ai': 'A chatbot that answers enrolment questions on a school website.',
 'term-algorithm': 'The steps to find the largest mark in a class list.',
 'term-api': 'A weather app requests <code>GET /forecast?city=Sydney</code> from the Bureau of Meteorology\'s servers.',
 'term-array': '<code>marks = [72, 85, 64]</code>, where <code>marks[1]</code> is 85.',
 'term-asymmetric-encryption': 'A browser encrypts a session key with a bank\'s public key; only the bank\'s private key can read it.',
 'term-attack-surface': 'Closing an unused admin login page removes one way in for attackers.',
 'term-authentication': 'Logging in with a password plus a code from an authenticator app.',
 'term-authorisation': 'A student can view their own results but only a teacher can edit them.',
 'term-availability': 'A school portal stays online during exam results release despite heavy traffic.',
 'term-backlog': '"Add dark mode" sits in the backlog below the higher-priority "Fix login bug".',
 'term-backpropagation': 'After predicting "cat" for a dog photo, the network nudges its weights to reduce that error.',
 'term-backend': 'The Flask server code that checks a login and queries the database.',
 'term-binary-search': 'Finding 21 in [3, 5, 8, 12, 17, 21, 26, 30] in two comparisons by halving the list.',
 'term-boolean': '<code>is_logged_in = True</code>',
 'term-cdn': 'A video site serves Sydney users from a Sydney server instead of one in the USA.',
 'term-cicd': 'Every push to GitHub runs the tests automatically and deploys if they pass.',
 'term-class': 'A <code>Student</code> class defines a name, ID and <code>enrol()</code> method.',
 'term-class-diagram': 'A box for <code>Book</code> listing <code>title</code>, <code>isbn</code> and <code>borrow()</code>, linked to <code>Library</code>.',
 'term-closed-loop': 'A robot vacuum uses a bump sensor to change direction when it hits a wall.',
 'term-code-review': 'A teammate spots a missing input check before a pull request is merged.',
 'term-cohesion': 'A <code>ReportPrinter</code> class that only formats and prints reports (high cohesion).',
 'term-confidentiality': 'Encrypting medical records so only the patient\'s doctor can read them.',
 'term-confusion-matrix': 'A spam filter with 90 true positives, 5 false positives, 8 false negatives and 97 true negatives.',
 'term-constructor': '<code>def __init__(self, name): self.name = name</code>',
 'term-cors': 'A server allows requests from <code>myschool.edu.au</code> but blocks scripts from other sites.',
 'term-coupling': 'A login module that calls a shared <code>UserService</code> rather than reading the database directly (loose coupling).',
 'term-csrf': 'A hidden form on a malicious page makes a logged-in user\'s browser transfer money.',
 'term-css': '<code>h1 { color: navy; }</code> makes every main heading navy.',
 'term-dast': 'Running OWASP ZAP against a live test site to find XSS vulnerabilities.',
 'term-data-dictionary': '<code>student_id</code> | integer | 8 digits | unique ID for each student.',
 'term-decision-tree': '"Is it raining?" → yes: take the bus; no: "Is it far?" → …',
 'term-degrees-of-freedom': 'A robot arm with a rotating base, shoulder and elbow has 3 DOF.',
 'term-desk-checking': 'Using a trace table to follow <code>i</code> and <code>total</code> through a loop by hand.',
 'term-devops': 'Developers and operations staff share one pipeline that builds, tests and monitors an app.',
 'term-digital-signature': 'A software update is signed so users can confirm it came from the real developer.',
 'term-dom': '<code>document.getElementById("score").textContent = 10;</code>',
 'term-encapsulation': 'A <code>BankAccount</code> hides <code>balance</code> and exposes <code>deposit()</code>.',
 'term-feasibility-analysis': 'Checking whether a booking app can be built in 10 weeks with the school\'s budget.',
 'term-flowchart': 'A diamond asks "age ≥ 18?" with yes and no arrows to different processes.',
 'term-frontend-framework': 'Building a quiz interface with React components.',
 'term-fsm': 'A traffic light cycling red → green → amber → red.',
 'term-functional-requirements': '"The system must let students book a library room."',
 'term-gantt': 'A bar for "Design" in weeks 1–2 and "Development" in weeks 3–6.',
 'term-generalisation': 'Moving <code>name</code> and <code>email</code> from <code>Student</code> and <code>Teacher</code> into a <code>Person</code> class.',
 'term-gui': 'A form with text boxes and a "Submit" button.',
 'term-hashing': 'Storing a password as its SHA-256 hash rather than as plain text.',
 'term-headless-cms': 'A school news site pulls articles from Strapi through an API.',
 'term-h-bridge': 'Reversing a robot\'s wheel motor by switching an L298N\'s inputs.',
 'term-html': '<code>&lt;h1&gt;Welcome&lt;/h1&gt;</code>',
 'term-http': 'A browser sends <code>GET /index.html</code> and the server replies <code>200 OK</code>.',
 'term-https': 'The padlock icon when logging in to online banking.',
 'term-i2c': 'An OLED display and a temperature sensor sharing the same two wires to an Arduino.',
 'term-ide': 'VS Code with its debugger and Git integration.',
 'term-inheritance': '<code>class Dog(Animal):</code> gives <code>Dog</code> everything <code>Animal</code> has.',
 'term-integrity': 'A checksum shows a downloaded installer has not been altered.',
 'term-interrupt': 'Pressing an emergency-stop button immediately halts a motor, whatever the program was doing.',
 'term-isr': 'A short function that sets <code>stop = True</code> when a button pin changes.',
 'term-iteration': '<code>for mark in marks: total += mark</code>',
 'term-javascript': 'Showing an error message when a form field is left empty.',
 'term-jwt': 'After login, the app sends a signed token with each request instead of a password.',
 'term-linear-regression': 'Predicting an exam score from hours studied.',
 'term-linear-search': 'Checking each name on a roll, one by one, until you find "Priya".',
 'term-logic-error': 'Using <code>&lt;</code> instead of <code>&lt;=</code>, so a mark of exactly 50 fails.',
 'term-logistic-regression': 'Predicting the probability that an email is spam.',
 'term-maintenance': 'Releasing version 1.1 to fix a bug reported after launch.',
 'term-manipulator': 'A two-finger gripper that picks up blocks.',
 'term-manifest': '<code>{"name": "Canteen App", "start_url": "/"}</code>',
 'term-mechatronics': 'An automatic irrigation system combining a moisture sensor, pump and control code.',
 'term-message-passing': '<code>cart.add(item)</code>: the checkout object sends a message to the cart object.',
 'term-method': '<code>account.withdraw(50)</code>',
 'term-microcontroller': 'An Arduino Uno or Raspberry Pi Pico.',
 'term-ml': 'A model that learns to recognise handwritten digits from thousands of examples.',
 'term-mlops': 'Automatically retraining and redeploying a recommendation model each month.',
 'term-mvc': 'Flask routes (controller) fetch data (model) and render a template (view).',
 'term-neural-network': 'A network with input, hidden and output layers that classifies photos of animals.',
 'term-non-functional-requirements': '"Pages must load within 2 seconds."',
 'term-nosql-database': 'Storing user profiles as JSON documents in MongoDB.',
 'term-object': '<code>s1 = Student("Ava")</code> creates one student object.',
 'term-observer-pattern': 'A score display updates automatically whenever the game\'s score changes.',
 'term-open-loop': 'A toaster that heats for a fixed time regardless of how brown the bread is.',
 'term-overfitting': 'A model scores 99% on training data but 60% on new data.',
 'term-penetration-testing': 'A hired ethical hacker tries to break into a school\'s student portal.',
 'term-peer-review': 'Swapping algorithms with a classmate to check each other\'s logic.',
 'term-pid': 'A drone adjusts motor speeds to hold a steady height despite wind.',
 'term-polling': 'A loop that checks <code>if button_pressed()</code> every few milliseconds.',
 'term-polymorphism': '<code>shape.area()</code> works for both a <code>Circle</code> and a <code>Square</code>.',
 'term-prototype': 'A clickable Figma mock-up shown to the client before coding.',
 'term-pseudocode': '<code>IF mark ≥ 50 THEN display "Pass" ENDIF</code>',
 'term-pwa': 'A news site that can be installed on a phone and read offline.',
 'term-pwm': 'Dimming an LED by switching it on 25% of the time.',
 'term-recursion': '<code>factorial(n) = n × factorial(n − 1)</code>, stopping at <code>factorial(1) = 1</code>.',
 'term-reinforcement-learning': 'A game-playing agent earns points for winning and learns better moves.',
 'term-requirements-elicitation': 'Interviewing library staff about how they currently track loans.',
 'term-rest': '<code>DELETE /api/students/42</code> removes student 42.',
 'term-runtime-error': 'Dividing by zero when a class has no students.',
 'term-sast': 'A tool such as Bandit scans Python source code for insecure functions.',
 'term-scrum': 'A daily stand-up, a two-week sprint, and a sprint review with the client.',
 'term-sdlc': 'Moving a canteen app from requirements through design, testing and maintenance.',
 'term-selection': '<code>if age &gt;= 18: print("Adult")</code>',
 'term-semi-supervised-learning': 'Labelling 100 photos by hand, then letting the model label 10,000 more.',
 'term-sensor': 'An ultrasonic sensor measuring the distance to a wall.',
 'term-sequence': 'Read two numbers, add them, then display the total.',
 'term-service-worker': 'Caching a timetable so it still opens with no signal.',
 'term-servo-motor': 'Setting a servo to 90° to point a camera straight ahead.',
 'term-singleton-pattern': 'One shared database connection object used across an app.',
 'term-spi': 'Reading data from an SD card module on an Arduino.',
 'term-sql-database': 'A <code>Students</code> table linked to an <code>Enrolments</code> table by <code>student_id</code>.',
 'term-sql-injection': 'Entering <code>\' OR 1=1 --</code> into a login box to bypass the password check.',
 'term-storyboard': 'Six sketched screens showing a student booking, paying and receiving a receipt.',
 'term-stepper-motor': 'Moving a 3D printer\'s print head exactly 0.1 mm.',
 'term-stride': 'Asking "Could someone spoof a teacher\'s login?" while reviewing a design.',
 'term-structure-chart': 'A "Process Results" module split into "Read Marks", "Calculate Average" and "Print Report".',
 'term-supervised-learning': 'Training on house photos labelled with their sale prices.',
 'term-symmetric-encryption': 'Encrypting a zip file with AES and sharing the same password with a friend.',
 'term-syntax-error': 'Forgetting the colon in <code>if x &gt; 5</code>.',
 'term-test-set': 'Keeping 20% of photos aside to measure the finished model\'s accuracy.',
 'term-tls': 'The encryption behind the padlock in a browser address bar.',
 'term-twos-complement': '−5 in 8 bits: 00000101 → invert to 11111010 → add 1 → 11111011.',
 'term-uart': 'An Arduino sending sensor readings to a laptop over USB serial.',
 'term-uml': 'A class diagram and a use case diagram for a library system.',
 'term-underfitting': 'Fitting a straight line to data that clearly curves.',
 'term-unit-testing': '<code>assert add(2, 3) == 5</code>',
 'term-unsupervised-learning': 'Grouping shoppers into clusters by buying habits, with no labels given.',
 'term-uat': 'The canteen manager tries the finished ordering app before it goes live.',
 'term-use-case-diagram': 'A "Student" actor linked to "Borrow Book" and "Return Book".',
 'term-user-stories': '"As a student, I want to see my timetable so that I know where to go."',
 'term-validation-set': 'Comparing models with 3, 5 and 7 layers on held-out data before the final test.',
 'term-variable': '<code>score = 0</code>',
 'term-version-control': '<code>git commit -m "Add login page"</code> saves a snapshot you can return to.',
 'term-waterfall': 'Finishing and signing off the full design before any code is written.',
 'term-wcag': 'Adding alt text so a screen reader can describe an image.',
 'term-wireframe': 'A grey-box sketch showing where the logo, menu and search bar go.',
 'term-white-box': 'Writing tests that make every IF statement take both its true and false paths.',
 'term-wagile': 'A fixed-date project with a planned design phase, then Agile sprints for development.',
 'term-xss': 'A comment containing <code>&lt;script&gt;</code> that runs in every reader\'s browser.',
}
